### ISSUE TITLE
npm package has invalid entrypoint

### ISSUE THREAD

**Issue by donmccurdy** [wnayes/glTF-js-utils#1]
Hi, thanks for publishing this utility to npm! There seems to be an issue with the main entrypoint in `package.json` though. I'm not familiar with publishing transpiled TypeScript modules, but I assume `"main": ".src/index.js"` should be `"main": "dist/index.js"`?

**Comment by wnayes** [comment]
I've published a v1.1.0 with a fix to the main entrypoint and removal of the outdated dist files.

**Comment by donmccurdy** [comment]
Thanks! Installing from NPM is working now. 👍
