### ISSUE TITLE
Module on npm is out of date

### ISSUE THREAD

**Issue by JoeLudwig** [wnayes/glTF-js-utils#13]
There's an error related to vertexColors that it looks like you've already fixed. Would you mind pushing a new version of your library to npm?

I'm using glTF-js-utils to generate glTF models on the fly in Aardvark: https://github.com/aardvarkxr/aardvark

It's been very helpful. Thanks for building it.

**Comment by wnayes** [comment]
Pushed a `v3.0.0` to npm.

**Comment by JoeLudwig** [comment]
Thanks!
