### ISSUE TITLE
Image as Texture

### ISSUE THREAD

**Issue by HotspurHN** [wnayes/glTF-js-utils#20]
Is it possible to use image like png buffer (not html image tag) for texture? I need that as Node js doesn't support html tags.

**Comment by wnayes** [comment]
Currently the supported types are `HTMLImageElement | HTMLCanvasElement`. I agree this would be limiting on Node. It should be a simple enhancement to take a buffer directly and I will consider it.

**Comment by wnayes** [comment]
This is released under v5.0.2. The Texture constructor now accepts ArrayBuffer and Data URL values. The data for these is expected to be PNG.
