### ISSUE TITLE
NPM build has a broken componentType switch, or outdated code?

### ISSUE THREAD

**Issue by donmccurdy** [wnayes/glTF-js-utils#3]
In the NPM build (https://bundle.run/gltf-js-utils@1.0.0/dist/index.js) I see a bad switch:

<img width="264" alt="screen shot 2018-08-15 at 3 07 22 pm" src="https://user-images.githubusercontent.com/1848368/44176035-0771ac80-a09d-11e8-9c98-801e669f772d.png">

Because of the missing `break;`, it falls through and hits the error for FLOAT component types. I don't see that bug in your source code, so either what's published to NPM is out of date, or bundle.run has a very strange compilation error. Any idea on this?

**Comment by donmccurdy** [comment]
Hm... I tried re-publishing the module myself from the master branch, compiling that with `bundle.run`, and the result is still broken. Maybe this is a bug in `bundle.run`...

**Comment by donmccurdy** [comment]
Ok, it's something about the TS->JS transpilation?

- https://github.com/wnayes/glTF-js-utils/blob/master/src/buffer.ts#L178-L183
- https://github.com/wnayes/glTF-js-utils/blob/master/dist/buffer.js#L142-L147

The JS version is not a

**Comment by wnayes** [comment]
It looks to me like I must have compiled the individual `.ts` files at an earlier state of development, and then eventually changed how the module build was done. They no longer change when I run `npm run build`, the only maintained output is the `/dist/gltfutils.js` UMD module.

I could delete the individual compiled files, or would it be useful to maintain those?

**Comment by donmccurdy** [comment]
Thanks! I’m not typically used to seeing individual files in a dist/ folder, so just having the one file would be fine from my perspective. Sounds like a fix for 
https://github.com/wnayes/glTF-js-utils/issues/1 would solve this as well — I only tried to use `index.js` because the default entry point didn’t work for me.

**Comment by donmccurdy** [comment]
Installing the latest version from NPM, I no longer have this issue. 🎉
