### ISSUE TITLE
Issues with mesh and vertex interface

### ISSUE THREAD

**Issue by donmccurdy** [wnayes/glTF-js-utils#4]
I'm struggling to export a mesh correctly _without_ materials or face colors, and I think this comes down to how the mesh and vertex interfaces are structured. In [this example](https://beta.observablehq.com/d/4b2e307950ac03c3), face colors and material index are both required arguments to `addFace`. When I export and validate the result (using http://github.khronos.org/glTF-Validator/) the model has some issues:

Errors:

Code | Message | Pointer
-- | -- | --
VALUE_NOT_IN_RANGE | Value 0 is out of range. | /bufferViews/3/byteLength
BUFFER_VIEW_TOO_LONG | BufferView does not fit buffer (0) byteLength (1152). | /bufferViews/3/byteOffset
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS | accessor.min and accessor.max must be defined for POSITION attribute accessor. | /meshes/0/primitives/0/attributes/POSITION
ACCESSOR_NON_UNIT | 36 accessor elements not of unit length: 0. [AGGREGATED] | /accessors/1

Info: 

Code | Message | Pointer
-- | -- | --
MESH_PRIMITIVE_UNUSED_TEXCOORD | Material does not use texture coordinates sets with indices (0). | /meshes/0/primitives/0/material
UNUSED_OBJECT | This object may be unused. | /bufferViews/3

I have a few suggestions, but they're pretty opinionated so I wasn't necessarily sure if you would agree or accept a PR:

- make vertex UVs, normals, and color nullable (https://github.com/wnayes/glTF-js-utils/blob/master/src/vertex.ts#L8-L15) so they aren't exported if they aren't set.
- remove color and material arguments from `addFace`, or make separate methods like `addFaceWithColor`.
- it looks like vertices are not de-duplicated (https://github.com/wnayes/glTF-js-utils/blob/master/src/mesh.ts#L14-L16); consider supporting indexed geometry
- some of this may be easier if the classes map more directly 1:1 with the basic glTF structure, e.g. not having face colors in the mesh class but providing utilities to convert face colors into vertex colors, but I don't know if that fits your needs for this project.

**Comment by wnayes** [comment]
My intention was to create a general purpose library, but the limitations it has reflect that there were only specific models I really needed to get working for my use case :smiley:.

- Making more of the properties optional sounds like a good idea.
- Definitely makes sense to not require face colors to add a face. Maybe the following signature for `addFace`? Basically make `materialIndex` default to -1 and optional.
```typescript
public addFace(v1: Vertex, v2: Vertex, v3: Vertex, materialIndex?: number = -1, color?: RGBColor | RGBAColor): void;
```
- Indexed geometry seems fine, keeping a way to at least turn it off would be my preference.
- I'm not opposed to changes to the classes. I lean towards keeping the concept of a face and face colors, even though they get turned into 3 repeated vertex colors in the end. It may have been nicer if I actually created a `Face` class (like `Face3` in three.js).

**Comment by wnayes** [comment]
I've adjusted the `addFace` API in v2.0.0 as described above. Several validator errors were also fixed.

**Comment by donmccurdy** [comment]
Great, thank you! :)
