### ISSUE TITLE
Question about creating geometry buffers

### ISSUE THREAD

**Issue by xeolabs** [wnayes/glTF-js-utils#5]
Hi, hope it's OK to ask this here: is it possible with this library to create a separate external binary buffer for each mesh?

Thanks!

**Comment by wnayes** [comment]
When doing a vanilla `exportGLTF` call, the object that it returns has a separate ArrayBuffer entry for each mesh. The only time it's not per mesh is when doing a GLB export and using the GLB's single big buffer as the output.

```
const gltfFiles = await GLTFUtils.exportGLTF(asset);
// {
//   "model.gltf": string /* JSON glTF string */
//
//   Each of these data bins is associated with a mesh.
//   "data1.bin": ArrayBuffer
//   "data2.bin": ArrayBuffer,
//   "data3.bin": ArrayBuffer,
//   ...
//   "img1.png": ArrayBuffer /* Texture image */
//   "img2.png": ArrayBuffer
//   ...
// }
```

**Comment by xeolabs** [comment]
Brilliant, thanks Will.
