### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by mrnexeon** [wnayes/glTF-js-utils#6]
Hello, there is error when I try to import glTF-js-utils
for example, click run https://npm.runkit.com/gltf-js-utils

Maybe I should do that in browser trough webpack?

**Comment by wnayes** [comment]
I pushed a patch version 2.0.2 out yesterday that changes the global that webpack uses. It looks like execution in runkit works now. Let me know if anything further doesn't work out in node.
